info:
  app:
    name: "@info.app.name@"
    version: "@info.app.version@"
    grailsVersion: "@info.app.grailsVersion@"
grails:
  codegen:
    defaultPackage: my.rest.app
  profile: rest-api
  views:
    default:
      codec: html
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      json:
        - application/json
        - text/json
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      js: text/javascript
      rss: application/rss+xml
      text: text/plain
      all: "*/*"
dataSource:
  pooled: true
  driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://localhost:1433;DatabaseName=MyDatabase
  username: my_user
  password: my_password
  dialect: org.hibernate.dialect.SQLServer2022Dialect

environments:
  development:
    dataSource:
      dbCreate: update
  test:
    dataSource:
      dbCreate: update
  production:
    dataSource:
      dbCreate: none
